version: '3.4'

services:
  # web:
  #   container_name: backend
  #   build: .
  #   ports:
  #     - '5000:5000'
  #   depends_on:
  #     - db
  #   environment:
  #     - PORT=$PORT
  #     - POSTGRES_USER=$POSTGRES_USERNAME
  #     - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  #     - POSTGRES_DB=$POSTGRES_DB
  #     - POSTGRES_HOST=$POSTGRES_HOST
  #     - POSTGRES_PORT=$POSTGRES_PORT
  #   command: npm run dev

  db:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
