version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
