version: '3.6'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USERNAME: '${POSTGRES_USERNAME}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./data:/var/lib/postgresql/data/
